// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { PingData, PingResponses, PingErrors, DecryptData, DecryptResponses, DecryptErrors, EncryptData, EncryptResponses, EncryptErrors, HashData, HashResponses, HashErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UmbracoCommunityEncryptionPropertyEditor {
    public static ping<ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<PingResponses, PingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/encryptionproperty/api/v1',
            ...options
        });
    }
    
    public static decrypt<ThrowOnError extends boolean = false>(options?: Options<DecryptData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<DecryptResponses, DecryptErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/encryptionproperty/api/v1/decrypt',
            ...options
        });
    }
    
    public static encrypt<ThrowOnError extends boolean = false>(options?: Options<EncryptData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<EncryptResponses, EncryptErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/encryptionproperty/api/v1/encrypt',
            ...options
        });
    }
    
    public static hash<ThrowOnError extends boolean = false>(options?: Options<HashData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<HashResponses, HashErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/encryptionproperty/api/v1/hash',
            ...options
        });
    }
}