// This file is auto-generated by @hey-api/openapi-ts

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/encryptionproperty/api/v1';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type DecryptData = {
    body?: never;
    path?: never;
    query?: {
        pw?: string;
        stringData?: string;
        key?: string;
        iv?: string;
    };
    url: '/umbraco/encryptionproperty/api/v1/decrypt';
};

export type DecryptErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type DecryptResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type EncryptData = {
    body?: never;
    path?: never;
    query?: {
        pw?: string;
        stringData?: string;
        key?: string;
        iv?: string;
        format?: string;
    };
    url: '/umbraco/encryptionproperty/api/v1/encrypt';
};

export type EncryptErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type EncryptResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type HashData = {
    body?: never;
    path?: never;
    query?: {
        pw?: string;
        password?: string;
        salt?: string;
    };
    url: '/umbraco/encryptionproperty/api/v1/hash';
};

export type HashErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type HashResponses = {
    /**
     * OK
     */
    200: string;
};

export type HashResponse = HashResponses[keyof HashResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44301' | (string & {});
};